---
title: "CSC 13"
author: "John Ryan Zelling \n Analyst"
date: "Jan 2017"
output: 
  pdf_document: 
    latex_engine: xelatex
    fig_height: 7.7
    fig_width: 7
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- ===== -->
<!-- TITLE -->
<!-- ===== -->

# CSC 13.0

```{r, echo=FALSE, results='asis', warning=FALSE}
source("CscString.R")
print(csc13.0.q)
```

^[
```{r, echo=FALSE, results='asis', warning=FALSE}
print(csc.lic)
```
]

<!-- ===== -->
<!-- PAGES -->
<!-- ===== -->

<P style="page-break-before: always"> \pagebreak

## CSC 13.1
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
library("png")
library("NLP")
library("RColorBrewer")
source("WordCloudGenerator.R")
WordCloudGenerator(csc13.1, "csc13.1")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.1)
```

<P style="page-break-before: always"> \pagebreak

## CSC 13.2
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc13.2, "csc13.2")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.2)
```

<P style="page-break-before: always"> \pagebreak

## CSC 13.3
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc13.3, "csc13.3")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.3)
```

<P style="page-break-before: always"> \pagebreak

## CSC 13.4
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc13.4, "csc13.4")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.4)
```

<P style="page-break-before: always"> \pagebreak

## CSC 13.5
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc13.5, "csc13.5")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.5)
```

<P style="page-break-before: always"> \pagebreak

## CSC 13.6
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc13.6, "csc13.6")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.6)
```

<P style="page-break-before: always"> \pagebreak

## CSC 13.7
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc13.7, "csc13.7")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.7)
```

<P style="page-break-before: always"> \pagebreak

## CSC 13.8
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc13.8, "csc13.8")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.8)
```

^[http://www.sei.cmu.edu/reports/13tn012.pdf]

<P style="page-break-before: always"> \pagebreak

## CSC 13.9
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc13.9, "csc13.9")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc13.9)
```
