---
title: "CSC 12"
author: "John Ryan Zelling \n Analyst"
date: "Jan 2017"
output: 
  pdf_document: 
    latex_engine: xelatex
    fig_height: 7.7
    fig_width: 7
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- ===== -->
<!-- TITLE -->
<!-- ===== -->

# CSC 12.0

```{r, echo=FALSE, results='asis', warning=FALSE}
source("CscString.R")
print(csc12.0.q)
```

^[
```{r, echo=FALSE, results='asis', warning=FALSE}
print(csc.lic)
```
]

<!-- ===== -->
<!-- PAGES -->
<!-- ===== -->

<P style="page-break-before: always"> \pagebreak

## CSC 12.1
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
library("png")
library("NLP")
library("RColorBrewer")
source("WordCloudGenerator.R")
WordCloudGenerator(csc12.1, "csc12.1")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.1)
```

^[http://www.team-cymru.org/bogon-reference.html]

<P style="page-break-before: always"> \pagebreak

## CSC 12.2
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.2, "csc12.2")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.2)
```

^[https://www.snort.org/]

<P style="page-break-before: always"> \pagebreak

## CSC 12.3
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.3, "csc12.3")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.3)
```

<P style="page-break-before: always"> \pagebreak

## CSC 12.4
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.4, "csc12.4")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.4)
```

<P style="page-break-before: always"> \pagebreak

## CSC 12.5
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.5, "csc12.5")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.5)
```

<P style="page-break-before: always"> \pagebreak

## CSC 12.6
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.6, "csc12.6")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.6)
```

<P style="page-break-before: always"> \pagebreak

## CSC 12.7
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.7, "csc12.7")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.7)
```

<P style="page-break-before: always"> \pagebreak

## CSC 12.8
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.8, "csc12.8")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.8)
```

<P style="page-break-before: always"> \pagebreak

## CSC 12.9
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.9, "csc12.9")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.9)
```

<P style="page-break-before: always"> \pagebreak

## CSC 12.10
```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
WordCloudGenerator(csc12.10, "csc12.10")
plot.new()
jj <- readPNG('wordcloud.png')
rasterImage(jj,-.3,-.3,1.3,1.3)
dev.off()
```

```{r, echo=FALSE, results='asis', warning=FALSE, fig.align='center', fig.width=7, fig.height=8}
plot.new()
qq <- readPNG('frequentwords.png')
rasterImage(qq,0,0,1.0,1.0)
dev.off()

print(csc12.10)
```
